# Generated by Django 3.2.15 on 2022-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('job_location', models.CharField(default='Gambia', max_length=100, verbose_name='Job Location')),
            ],
            options={
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='Get in touch', max_length=100)),
                ('paragraph', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.')),
                ('address_one', models.CharField(max_length=100)),
                ('address_two', models.CharField(max_length=100)),
                ('phone_1', models.IntegerField()),
                ('phone_2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_line_1', models.IntegerField()),
                ('telephone_line_2', models.IntegerField(blank=True, null=True)),
                ('map_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_asked', models.CharField(max_length=255, verbose_name='Question Asked')),
                ('question_answer', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_summary', models.TextField(default='lorem ipsum nakalas')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('role', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, height_field=650, null=True, upload_to='team/', width_field=650)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('google', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_paragraph', models.TextField()),
                ('testimonial_by', models.CharField(max_length=200)),
                ('testimonial_by_profession', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
