# Generated by Django 3.2.15 on 2022-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Youtube URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Linkedin URL')),
                ('flickr_url', models.URLField(blank=True, null=True, verbose_name='Flickr URL')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type_of_stakeholder', models.CharField(choices=[('Donor', 'Donor'), ('Organization', 'Organization'), ('Institutional Partner', 'Institutional Partner')], default='Donor', max_length=255, verbose_name='Type of Stakeholder')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
            },
        ),
    ]
