# Generated by Django 3.2.15 on 2022-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField(verbose_name='Youtube Link')),
                ('image_background', models.ImageField(height_field=562, upload_to='about_us', verbose_name='Image Background', width_field=602)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_1', models.CharField(max_length=255, verbose_name='Heading One')),
                ('heading_2', models.CharField(max_length=255, verbose_name='Heading Two')),
                ('short_paragraph', models.TextField(verbose_name='Short Paragraph')),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(height_field=260, upload_to='what_we_do', verbose_name='Card Image', width_field=360)),
                ('card_title', models.CharField(max_length=255, verbose_name='Card Title')),
                ('card_text', models.TextField(verbose_name='Card Text')),
            ],
            options={
                'verbose_name_plural': 'What We Do',
            },
        ),
    ]
